variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "instance_type" {}
variable "pub_key_name" {}
variable "image_name" {}
variable "availability_zone" {}
variable "vpc_name" {}